services:
  server:
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "fresh"

  nuxt:
    container_name: nuxt
    build: .
    ports:
      - 3000:3000
    volumes:
      - /app
      - /node_modules
    stdin_open: true
    tty: true
    command: sh -c "bun && bun run dev"

  db_auth:
    container_name: db_auth
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=8008
    image: postgres
