services:
  server:
    build:
      context: .
      target: final
    ports:
      - 4000:4000
  db_auth:
    container_name: db_auth
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=8008
    image: postgres
